[package]
name = "test_card_deck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
card_deck = { path = "../card_deck" }
rand = "0.3.14"
