[package]
name = "test_lalgebra_vector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lalgebra_vector = { path = "../lalgebra_vector" }