[package]
name = "test_diamond_creation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diamond_creation = { path = "../diamond_creation" }